### ISSUE TITLE
Do ur codes using Sync_Batchnorm in default?

### ISSUE THREAD

**Issue by Fred199683** [kakaobrain/scrl#10]
First of all ,  i am very interested in your paper.
Since your model is based on BYOL, I think the BN layer is very important in projector and predictor, and it's beneficial from large batch-size. 
Since your code is working with DDP, i didn't find the Sync_Batchnorm.....i think it's weird.... If u don't use Sync-BN, so the BN is calculated only in each single gpu but not share with other gpus.
I think maybe i make a mistake, so do ur codes using Sync_Batchnorm in default? Should we use SyncBN?
Hope anyone can answer my question, Thx!

**Comment by ricoshin** [comment]
Thank you for your interest in our work!
I think you overlooked this line: https://github.com/kakaobrain/scrl/blob/master/utils/utils.py#L45
