### ISSUE TITLE
problem about generating bboxes in intersection area

### ISSUE THREAD

**Issue by UcanSee** [kakaobrain/scrl#2]
Thanks for sharing such wonderful work! it's so amazing! Now I am trying to reproduce your work, but I meet some problem about generating bboxes in intersection area.  According to your paper, you use some operation similar to RandomResizedCrop to generate two views and compute intersection between these two views, but how to ensure these two views always have overlaps. In addition, I found that even if two views have overlaps,  there are some image which can not generate enough bboxes, for example, 10. Is there some other operation to solve this problem? Can you give me some suggestion?

**Comment by ricoshin** [comment]
First of all, we use a more generous cropping scale in the range of [0.2, 1.0], inducing more frequent overlap between the two views. Despite that, if the two views happen to have no intersection area, they are simply excluded from the mini-batch. Then, in both views, we try to progressively sample boxes that meet the given IoU condition(<0.5) between all the previously sampled ones. If we keep failing for a sufficient number of attempts(= 50), we just stop there and move on to the next pairs. While this heuristic varies the number of boxes pooled per mini-batch, we found that it works empirically well. For other details not described here, please refer to the code that will be released soon. Thank you for your interest! (cc. @prayforher)

**Comment by UcanSee** [comment]
Thanks for your answers very much, I've got it!
